# Default values for mongodb-enterprise-standalone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod
  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.2.4

database:
  name: mongodb-enterprise-database

opsManager:
  enable: false
  image: mongodb-enterprise-ops-manager
  name: ops-manager
  version: 4.2.0
  adminCredentials:
    FirstName: "ops-manager"
    LastName: "admin"
    Password: "Passw0rd."
    Username: "ops-manager-admin"
    Email: "admin@example.org"

cloudManager:
  enable: true
  publicApiKey: NGKMIHEO
  privateApiKey: 66bcc7de-b0de-4d8d-9695-ef97637c6895 
  orgId: 5d371dda553855dd17d4fcf9

registry:
  # Specify if images are pulled from private repository
  imagePullSecrets:
  pullPolicy: Always
  repository: quay.io/mongodb
  image: mongodb-enterprise-operator

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true

  

version: 4.0.0
persistent: true
podSpec:
  cpu: '0.25'
  memory: 512M
  storage: 12G
  storageClass: standard




