---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.version}}
  type: Standalone
  project: {{ .Release.Name }}-cloud-manager-config
  credentials: {{ .Release.Name }}-cloud-manager-secret

  # This flag allows the creation of pods without persistent volumes. This is for
  # testing only, and must not be used in production. 'false' will disable
  # Persistent Volume Claims. The default is 'true'
  persistent: true 
